language: node_js

node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"

before_script:
  - "./start-local-hbase.sh"

script: "make test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
